// <auto-generated />
namespace Webshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class contextmerge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contextmerge));
        
        string IMigrationMetadata.Id
        {
            get { return "201606091554032_contextmerge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
